import numpy as np
import pytest
from qsimov.paths.maxpooling import get_all_paths_maxpool_layer
from qsimov.paths.conv import _side_shape_to_channels_first
import torch
import torch.nn.functional as F
import tensorflow as tf


def _flatten_and_insert_one(inputs):
    return np.insert(np.reshape(inputs, (inputs.shape[0], -1)), 0, 1, axis=1)


@pytest.mark.parametrize("data_format", ["channels_last", "channels_first"])
@pytest.mark.parametrize(
    "input_shape, pool_size, strides, padding",
    [
        ((32, 32, 32, 3), (2, 2, 2), (2, 2, 2), "valid"),
        ((16, 16, 16, 6), (3, 3, 3), (1, 1, 1), "valid"),
        ((32, 32, 16, 4), (2, 2, 1), (2, 2, 1), "valid"),
        ((8, 8, 8, 5), (2, 2, 2), (1, 1, 1), "same"),
        ((16, 64, 8, 2), (3, 3, 1), (1, 1, 1), "valid"),
    ],
)
def test_get_all_paths_maxpool_by_flattening(
    input_shape, pool_size, strides, padding, data_format
):
    # As it is hard to design test cases for maxpooling, we use the generated
    # paths to manually compute the layer output and then compare the output
    # with the true output generated by the keras/torch maxpooling layer.
    input_shape = np.array(input_shape)

    # adapt to channels first testcase
    if data_format == "channels_first":
        input_shape = _side_shape_to_channels_first(input_shape)

        # padding is not supported in torch as str for maxpooling
        padding = (1, 1, 1) if padding == "same" else (0, 0, 0)

        # random input for layer float 32
        input_to_layer = torch.rand((1, *input_shape)).to(torch.float32)

        # compute output using torch (it uses channels first)
        output = F.max_pool3d(input_to_layer, pool_size, strides, padding)
        output = output.numpy().ravel()
    else:
        input_to_layer = tf.random.normal((1, *input_shape))

        # compute output using keras (it uses channels last)
        output = tf.keras.layers.MaxPool3D(pool_size, strides, padding)
        output = output(input_to_layer).numpy().ravel()

    # get paths between layers
    paths_layer = get_all_paths_maxpool_layer(
        input_shape, pool_size, strides, padding, data_format
    )

    # flatten input
    input_to_layer = input_to_layer.numpy().ravel()

    # use paths to manually compute output
    output_computed = np.full(len(output), -np.inf)
    for path in paths_layer - 1:  # -1 because paths are 1-indexed
        output_computed[path[1]] = max(
            output_computed[path[1]], input_to_layer[path[0]]
        )

    np.testing.assert_array_almost_equal(output_computed, output)
